### PR TITLE
Check each stage has given the correct output, warn if not

### PR DESCRIPTION
**Pull request by EuanPyle**
Useful for IDing where things have gone wrong, esp. if AreTomo is not loaded properly.

### CODE REVIEW

**Comment by EuanPyle** [comment]
Also added  a few lines to check whether the given tomogram name (if provided) actually exists in rlnTomoName

**Comment by alisterburt** [comment]
I think this PR is overall a little too 'defensive', I would rather delegate this sort of thing to checks within `yet_another_imod_wrapper` and `lil_aretomo`, what do you think?

What was the case you had which passed the AreTomo on PATH test or executable was provided but wasn't working properly? It might help me to understand the motivations a little better

> Also added a few lines to check whether the given tomogram name (if provided) actually exists in rlnTomoName

This absolutely should be added - do you mind piecing it out into its own PR so it can go in directly?

Thanks dude!

**Comment by EuanPyle** [comment]
Hah, I thought that I should have put the tomogram name check in a seperate PR immeditaely after committing - will do!

Re: the other stuff, it can mostly not really be included. Sometimes when I did something wrong the program would crash without an error message which I thought might be a problem but I think the way the GUI will be set up those problems won't come about (esp. the tilt stack generation and the star file generation checks). 

One thing I do want to include is a check that AreTomo has been installed correctly by the user. One thing I can forsee is the user not really knowing whether their version of AreTomo can be called without providing an exe or whtether they need to give a path to the exe. I thought a good way to check would be to see if the .xf file is produced: if its not I think that would mean how to run AreTomo is not correctly specificed by the user. Another way could be to try and run: AreTomo --help and see if there's an output like your imod_is_installed() check...that may be better actually...

**Comment by EuanPyle** [comment]
Just realised there was already a check for whther AreTomo is available in lil_aretomo ... ignore this PR! Sorry!

**Comment by alisterburt** [comment]
https://github.com/alisterburt/yet-another-imod-wrapper/blob/c99eb751ccca59d83400f734dd8af621954ecd5c/yet_another_imod_wrapper/utils.py#L14-L16 is how I'm doing the check now for IMOD now, this is called here when you run an alignment https://github.com/alisterburt/yet-another-imod-wrapper/blob/c99eb751ccca59d83400f734dd8af621954ecd5c/yet_another_imod_wrapper/fiducials.py#L40-L43

I think I added the install check to lil_aretomo but didn't actually call it, that could be done here https://github.com/EuanPyle/lil_aretomo/blob/e1f349ba662ee54c0db12602b0ec7625d930e9ec/lil_aretomo/utils.py#L28-L42

**Comment by EuanPyle** [comment]
[def check_aretomo_availability():
    """Check for an installation of AreTomo on the PATH."""
    return shutil.which('AreTomo') is not None](https://github.com/EuanPyle/lil_aretomo/blob/e1f349ba662ee54c0db12602b0ec7625d930e9ec/lil_aretomo/utils.py#L90-L92)
    
Yup, think it's here and is called here already! 

https://github.com/EuanPyle/lil_aretomo/blob/e1f349ba662ee54c0db12602b0ec7625d930e9ec/lil_aretomo/aretomo.py#L46-L49

**Comment by EuanPyle** [comment]
I will modify it so that it will do the same check on the exe, if provided

**Pull request closed without merging**
